### ISSUE TITLE
boilerplate.h: No such file or directory

### ISSUE THREAD

**Issue by starboy-3** [alexandru-dinu/igcc#14]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/72921287/149664439-ee886d08-8bc9-44cc-9e1f-960b95b55ce0.png">

**Comment by starboy-3** [comment]
@alexandru-dinu

**Comment by alexandru-dinu** [comment]
Hi,

You have to start the REPL using `./igcc -I libigcc`, since that's the directory containing `boilerplate.h`:

![image](https://user-images.githubusercontent.com/14110183/149670972-3c7eb3a5-c3a6-4bea-a224-06de9743c44e.png)

**Comment by starboy-3** [comment]
@alexandru-dinu Thanks! Cool tool!

**Comment by alexandru-dinu** [comment]
Well, it's certainly the merit of @andybalaam as the original creator!
