### ISSUE TITLE
what's the difference between iGCC and cling ?

### ISSUE THREAD

**Issue by sequoiar** [alexandru-dinu/igcc#17]

**Comment by jpivarski** [comment]
https://github.com/root-project/cling

**Comment by alexandru-dinu** [comment]
Haven't heard of `cling` up until now, good stuff, thanks for mentioning it.

The purpose of this repo is to attempt to maintain `igcc` (wrote by @andybalaam) which was previously hosted at https://sourceforge.net/projects/igcc/

`cling` looks like a more complex, mature and feature-rich project, whereas `igcc` is essentially a very simple intermediary between user prompts and gcc.
