### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by MaddyGuthridge** [alexandru-dinu/igcc#18]
It'd be cool if this was published on pypi to allow for easy installation using `pipx`.

**Comment by alexandru-dinu** [comment]
You inspired me to clean-up the package setup a bit and make it easier to install.
I'll maybe push this to PyPI at a later time, but in the meantime this can be used:
```
pip3 install git+https://github.com/alexandru-dinu/igcc.git
```
Which will install an executable script: `igcc`, so you can immediately run the REPL.

By default, the [`assets/`](https://github.com/alexandru-dinu/igcc/tree/main/igcc/assets) include dir is available, providing access to [`boilerplate.h`](https://github.com/alexandru-dinu/igcc/blob/main/igcc/assets/boilerplate.h).

**Comment by MaddyGuthridge** [comment]
Awesome, `pipx install git+https://github.com/alexandru-dinu/igcc.git` worked perfectly!
